// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8GgDR-sFhBnUyOkrOtgJcySgKfV29uW4',
    appId: '1:938677052316:android:faa54828b03a3e0042de59',
    messagingSenderId: '938677052316',
    projectId: 'nutrilens-d6670',
    databaseURL: 'https://nutrilens-d6670-default-rtdb.firebaseio.com',
    storageBucket: 'nutrilens-d6670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5h1oH_dMm46XOCqQIMCNbAEoWFi_tyOA',
    appId: '1:938677052316:ios:8c6f57052597d2fd42de59',
    messagingSenderId: '938677052316',
    projectId: 'nutrilens-d6670',
    databaseURL: 'https://nutrilens-d6670-default-rtdb.firebaseio.com',
    storageBucket: 'nutrilens-d6670.firebasestorage.app',
    iosBundleId: 'com.example.nutrilens',
  );
}
